# This is a basic workflow to help you get started with Actions

name: Change _config.yml url

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Find and Replace
  # You may pin to the exact commit or the version.
  # uses: jacobtomlinson/gha-find-replace@c395d06fcfaa7202ea69c49dbac56eb7f35ca96f
        uses: jacobtomlinson/gha-find-replace@0.1.2
        with:
    # A regular expression of files to include in our find and replace
          include: _config.yml
    # The string we want to replace
          find: '/CodingGuidelines"'
     # The new string to replace with
          replace: '/CodingGuidelinesSite"'
          
      - name: Create commit and push
        run: |
          git config user.name '${{ github.actor }}'
          git config user.email '${{ github.actor }}@users.noreply.github.com'
          git add -A
          git commit -m "Changed config.yml url to use CodingGuidelinesSite"
          git push origin '${{ github.ref }}' 
